name: Cron Fetch Proxies

on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2 
    
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Pull files
        run: |
          git config --local user.email "mastermind@moviescomplex.live"
          git config --local user.name "Master-Mind-007"
          git pull origin main
      
      - name: Get proxies
        run: python getproxy.py

      - name: Commit files
        run: |
          git add -A
          git commit -m "Update Proxies (`date '+%F %H:%M %Z'`)" -a
          git branch -u origin/main
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          branch: main 
